// import { Geist, Geist_Mono } from "next/font/google";
"use client";
import NavBar from "@/components/NavBar";
import "bootstrap/dist/css/bootstrap.min.css";
// import "./globals.css";
import { useEffect } from "react";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  useEffect(() => {
    if (typeof window !== undefined) {
      require("bootstrap/dist/js/bootstrap.bundle.js");
    }
  }, []);
  return (
    <html lang="en">
      <body>
        <NavBar />
        <div className="container">{children}</div>
      </body>
    </html>
  );
}
